version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: node server.js

  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
